name: Anime App Workflow
on:
    push:
        branches: [master]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /var/www/html/AnimePedia/
                      git pull origin master
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      git status
                      npm install
                      npm run build
