name: Anime App Workflow
on:
    push:
        branches: [master]
jobs:
    deploy:
        runs-in: ubuntu-latest

        steps:
            - name: Connect to Server Use SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: whoami
